version: 2
jobs:
  php-composer-phpunit:
    machine: true
    steps:
      - checkout
      - run:
          command: make php-composer-phpunit
  php-no-libraries:
    machine: true
    steps:
      - checkout
      - run:
          command: make php-no-libraries
workflows:
  version: 2
  test:
    jobs:
      - php-composer-phpunit
      - php-no-libraries
