version: 2.1
jobs:
  php-composer-phpunit:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make php-composer-phpunit
  javascript-axios:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make javascript-axios
  javascript-jest-puppeteer:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make javascript-jest-puppeteer
  javascript-cypress-js:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make javascript-cypress-js
  ruby-rspec:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make ruby-rspec
  ruby-cucumber-test:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make ruby-cucumber-test
  python2-pytest:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make python2-pytest
workflows:
  version: 2
  test:
    jobs:
      - php-composer-phpunit
      - javascript-axios
      - javascript-jest-puppeteer
      - javascript-cypress-js
      - ruby-cucumber-test
      - ruby-rspec
      - python2-pytest
