version: 2
jobs:
  php-composer-phpunit:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make php-composer-phpunit
  javascript-axios:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make javascript-axios
  javascript-jest-puppeteer:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make javascript-jest-puppeteer
  javascript-cypress-js:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make javascript-cypress-js
  ruby-rspec:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run:: make ruby-rspec
  ruby-cucumber-test:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run:: make ruby-cucumber-test
workflows:
  version: 2
  test:
    jobs:
      - php-composer-phpunit
      - javascript-axios
      - javascript-jest-puppeteer
      - javascript-cypress-js
      - ruby-cucumber-test
      - ruby-rspec
