version: 2.1
jobs:
  php-composer-phpunit:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make php-composer-phpunit
  javascript-axios:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make javascript-axios
  javascript-jest-puppeteer:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make javascript-jest-puppeteer
  java-maven-junit4:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make java-maven-junit4
  java-maven-selenium:
    docker:
      - image: circleci/openjdk:8-jdk-stretch-browsers
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make java-maven-selenium
  javascript-cypress-js:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make javascript-cypress-js
  javascript-webdriver-io:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make javascript-webdriver-io
  ruby-rspec:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make ruby-rspec
  ruby-cucumber-test:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make ruby-cucumber-test
  python2-pytest:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make python2-pytest
  golang:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: make golang
  csharp-dotnet-core3:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: cd csharp-dotnet-core3 && dotnet restore && dotnet build && dotnet test
  csharp-dotnet-core2-selenium:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run: cd csharp-dotnet-core2-selenium; cdotnet.exe restore
      - run: cd csharp-dotnet-core2-selenium; dotnet.exe install
      - run: cd csharp-dotnet-core2-selenium; dotnet.exe test
workflows:
  version: 2
  test:
    jobs:
      - php-composer-phpunit
      - javascript-axios
      - javascript-jest-puppeteer
      - javascript-cypress-js
      - javascript-webdriver-io
      - ruby-cucumber-test
      - ruby-rspec
      - python2-pytest
      - golang
      - java-maven-junit4
      - java-maven-selenium
      - csharp-dotnet-core3
      - csharp-dotnet-core2-selenium
